name: JUnit Tests with Maven

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 19
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '19'
        architecture: 'x64'
      
    - name: Build with Maven
      run: mvn -B clean package --file ./ufund-api/pom.xml
      
    - name: Run JUnit tests
      run: mvn -B test --file ./ufund-api/pom.xml
